openapi: 3.0.0
info:
  title: Education and Work Plan API
  version: '1.0.0'
  description: Education and Work Plan API
  contact:
    name: Matt Wills
    email: matt.wills@digital.justice.gov.uk
servers:
  - url: 'http://localhost:3000'
#
# --------------------------------------------------------------------------------
#
paths:
  #
  # --------------------------------------------------------------------------------
  # RESTful style endpoints start here
  # --------------------------------------------------------------------------------
  #

  #
  # Goals
  # --------------------------------------------------------------------------------
  '/action-plans/{prisonNumber}':
    parameters:
      - name: prisonNumber
        description: The number of the Prisoner who may have created (or is in the process of creating) an "Action Plan", consisting of one or more Goals. The prisonNumber is the unique identifier of the Action Plan.
        schema:
          type: string
        example: 'A1234BC'
        in: path
        required: true
    get:
      summary: Return a Prisoner's Action Plan
      description: Return a Prisoner's Action Plan
      tags:
        - Action Plan
      responses:
        '200':
          $ref: '#/components/responses/ActionPlan'
        '404':
          $ref: '#/components/responses/404ErrorResponse'
      operationId: get-action-plan-by-prison-number

  '/action-plans/{prisonNumber}/goals':
    parameters:
      - name: prisonNumber
        description: The number of the Prisoner who may have created (or is in the process of creating) an "Action Plan", consisting of one or more Goals. The prisonNumber is the unique identifier of the Action Plan.
        schema:
          type: string
        example: 'A1234BC'
        in: path
        required: true
    post:
      summary: Creates a Goal.
      description: Creates a Goal and saves it to the Prisoner's Action Plan (the latter will be created if it doesn't already exist).
      tags:
        - Action Plan - Single Goal
      responses:
        '201':
          $ref: '#/components/responses/Goal'
        '400':
          $ref: '#/components/responses/400ErrorResponse'
        '404':
          $ref: '#/components/responses/404ErrorResponse'
      operationId: create-goal
      requestBody:
        $ref: '#/components/requestBodies/CreateGoal'

#
# --------------------------------------------------------------------------------
#
components:
  #
  # Schema and Enum Definitions
  # --------------------------------------------------------------------------------
  schemas:
    ErrorResponse:
      title: ErrorResponse
      description: |
        A generic response body object describing errors in a web request, and can be used to communicate several
        different types of error condition such as (but not limited to) `400 BAD REQUEST`, `409 CONFLICT` etc.
      properties:
        timestamp:
          type: string
          format: date-time
          example: '2022-09-28T18:01:42.105Z'
        status:
          type: integer
          example: 400
        error:
          type: string
          example: 'Bad Request'
        message:
          type: string
          example: 'Validation failed for object=createGoalRequest. Error count: 1'
        validationErrors:
          description: Validation errors are only present if the error being described is a `400 BAD REQUEST`.
          type: array
          items:
            type: string
          example: 'Error on field goal.reviewDate: rejected value [2023-06-01] cannot be in the past'
      required:
        - timestamp
        - status
        - error
        - message
    ActionPlanResponse:
      title: ActionPlanResponse
      type: object
      description: A Prisoner's Action Plan containing a list of one or more Goals.
      properties:
        prisonNumber:
          type: string
          description: The ID of the prisoner
          example: 'A1234BC'
        goals:
          type: array
          description: A List of at least one or more Goals.
          items:
            $ref: '#/components/schemas/GoalResponse'
      required:
        - prisonNumber
        - goals
    GoalResponse:
      title: GoalResponse
      type: object
      description: An individual Goal that a Prisoner aims to complete as part of their Action Plan. The goal will be active to start with.
      properties:
        goalReference:
          type: string
          description: The Goal's unique reference
          example: c88a6c48-97e2-4c04-93b5-98619966447b
        title:
          type: string
          description: A title explaining the aim of the goal.
          example: Improve communication skills
        reviewDate:
          type: string
          format: date
          description: An ISO-8601 date representing when the Goal is up for review.
          example: '2023-12-19'
        status:
          $ref: '#/components/schemas/GoalStatus'
        steps:
          type: array
          minItems: 1
          description: A List of at least one Step.
          items:
            $ref: '#/components/schemas/StepResponse'
        notes:
          type: string
          description: Some additional notes related to the Goal.
          example: Pay close attention to Peter's behaviour.
        createdBy:
          type: string
          description: The name/ID of the person who created the goal. **Note that this is a placeholder for now currently not populated.**
          example: 'TBD'
        createdAt:
          type: string
          format: date-time
          description: An ISO-8601 timestamp representing when the Goal was created.
          example: '2023-06-19T09:39:44Z'
        updatedBy:
          type: string
          description: The name/ID of the person who last updated the goal. **Note that this is a placeholder for now currently not populated.**
          example: 'TBD'
        updatedAt:
          type: string
          format: date-time
          description: An ISO-8601 timestamp representing when the Goal was last updated. This will be the same as the created date if it has not yet been updated.
          example: '2023-06-19T09:39:44Z'
      required:
        - goalReference
        - title
        - reviewDate
        - status
        - steps
        - createdBy
        - createdAt
        - updatedBy
        - updatedAt
    StepResponse:
      title: StepResponse
      type: object
      description: A Step within a Goal that must be completed in order for the overall Goal to be completed.
      properties:
        stepReference:
          type: string
          description: A unique reference for the Step
          example: d38a6c41-13d1-1d05-13c2-24619966119b
        title:
          type: string
          description: A title describing the step
          example: Book communication skills course
        targetDate:
          type: string
          format: date
          description: A date by which the prisoner should aim to complete the step.
          example: '2023-08-19'
        status:
          $ref: '#/components/schemas/StepStatus'
        sequenceNumber:
          type: integer
          description: The number (position) of the Step within the overall Goal.
          example: 1
      required:
        - stepReference
        - title
        - targetDate
        - status
        - sequenceNumber

    CreateGoalRequest:
      title: CreateGoalRequest
      type: object
      description: A request to create an individual Goal that a Prisoner aims to complete as part of their Action Plan. The goal's status will be set to 'ACTIVE'.
      properties:
        title:
          type: string
          description: A title explaining the aim of the goal.
          example: Improve communication skills
        reviewDate:
          type: string
          format: date
          description: An ISO-8601 date representing when the Goal is up for review.
          example: '2023-12-19'
        steps:
          type: array
          minItems: 1
          description: A List of at least one Step.
          items:
            $ref: '#/components/schemas/CreateStepRequest'
        notes:
          type: string
          description: Some additional notes related to the Goal.
          example: Pay close attention to Peter's behaviour.
      required:
        - title
        - reviewDate
        - steps
    CreateStepRequest:
      title: CreateStepRequest
      type: object
      description: A request to create a Step within a Goal. The Step is created a status of NOT_STARTED.
      properties:
        title:
          type: string
          description: A title describing the step
          example: Book first aid course
        targetDate:
          type: string
          format: date
          description: A date by which the prisoner should aim to complete the step.
          example: '2023-12-19'
        sequenceNumber:
          type: integer
          description: The number (position) of the Step within the overall Goal.
          example: 1
      required:
        - title
        - targetDate
        - sequenceNumber

    GoalStatus:
      title: GoalStatus
      description: Enum describing the various statuses of a Goal's lifecycle.
      type: string
      enum:
        - ACTIVE
        - COMPLETE
        - ARCHIVED
    StepStatus:
      title: StepStatus
      description: Enum describing the various statuses of a Step's lifecycle.
      type: string
      enum:
        - NOT_STARTED
        - ACTIVE
        - COMPLETE

  #
  # Response Body Definitions
  # --------------------------------------------------------------------------------
  responses:
    400ErrorResponse:
      description: Error response for a HTTP 400 describing fields in the request payload that are in error.
      headers:
        Access-Control-Allow-Origin:
          schema:
            type: string
        Access-Control-Allow-Methods:
          schema:
            type: string
        Access-Control-Allow-Headers:
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            timestamp: '2023-06-20T18:01:42.105Z'
            status: 400
            error: 'Bad Request'
            message: 'Validation failed for object=createGoalRequest. Error count: 1'
            validationErrors: 'Error on field goal.reviewDate: rejected value [2023-06-01] cannot be in the past'
    404ErrorResponse:
      description: |
        Error response for a HTTP 404 describing the problem with the request.
      headers:
        Access-Control-Allow-Origin:
          schema:
            type: string
        Access-Control-Allow-Methods:
          schema:
            type: string
        Access-Control-Allow-Headers:
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            timestamp: '2023-06-20T18:01:42.105Z'
            status: 404
            error: 'Not Found'
            message: 'The prisoner with prisonNumber=[A1234BC] not found'
    409ErrorResponse:
      description: |
        Error response for a HTTP 409 describing the problem with the request.
      headers:
        Access-Control-Allow-Origin:
          schema:
            type: string
        Access-Control-Allow-Methods:
          schema:
            type: string
        Access-Control-Allow-Headers:
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            timestamp: '2022-09-28T18:01:42.105Z'
            status: 409
            error: 'Conflict'
            message: 'A Goal with reference [c88a6c48-97e2-4c04-93b5-98619966447b] has an unexpected status = ARCHIVED'
    ActionPlan:
      description: Response body containing the Goals that make up a Prisoner's Action Plan.
      headers:
        Access-Control-Allow-Origin:
          schema:
            type: string
        Access-Control-Allow-Methods:
          schema:
            type: string
        Access-Control-Allow-Headers:
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ActionPlanResponse'
    Goal:
      description: Response body containing a single Goal within a Prisoner's Action Plan.
      headers:
        Access-Control-Allow-Origin:
          schema:
            type: string
        Access-Control-Allow-Methods:
          schema:
            type: string
        Access-Control-Allow-Headers:
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GoalResponse'

  #
  # Request Body Definitions
  # --------------------------------------------------------------------------------
  requestBodies:
    CreateGoal:
      description: Request body to create a single Goal.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateGoalRequest'
